# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: 'Publish'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
      tag:
        description: 'tag'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --frozen-lockfile --ignore-scripts

      - run: yarn test

      - name: Set Git credentials
          run: |
            git config --local user.email "bumbledos@gmail.com"
            git config --local user.name "ArthurStam"

      - run: yarn version --new-version ${{ github.event.inputs.version }}

      - run: yarn publish --non-interactive --tag ${{ github.event.inputs.tag }}
        if: ${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: yarn publish --non-interactive
        if: ${{ !github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Pushing changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Creating doc
        run: |
          yarn doc:build
          mkdir ${{ github.event.inputs.version }}
          cp -R styleguide/* ${{ github.event.inputs.version }}
          mv ${{ github.event.inputs.version }} styleguide/${{ github.event.inputs.version }}
        if: ${{ !github.event.inputs.tag }}

      - name: Creating doc
        run: |
          yarn doc:build --dist styleguide/${{ github.event.inputs.version }}
        if: ${{ github.event.inputs.tag }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: styleguide # The folder the action should deploy.
